# local 환경
spring:
  profiles:
    default: local
  datasource:
#    url: jdbc:mysql://localhost:3306/mydb
    url: jdbc:mysql://host.docker.internal:3306/mydb
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
#       host: localhost
       host: cache-server # compose.yml 참고
       port: 6379 # default
  logging:
     level:
       org.springframework.cache: trace # Redis 사용에 대한 로그가 조회되도록 설정

---

# prod 환경
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://test-db.cv28mqsa8pf8.us-east-1.rds.amazonaws.com:3306/mydb
    username: admin
    password: password